name: Build Minecraft Plugin

on:
  workflow_dispatch: # 手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 JDK 环境
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # 根据你的项目需求选择合适的 JDK 版本
          distribution: 'temurin'

      # 授予 gradlew 执行权限
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 构建项目并生成 Shadow JAR
      - name: Build with Gradle (ShadowJar)
        run: ./gradlew clean shadowJar

      # 提取版本号（从 gradle.properties 中读取）
      - name: Extract version from gradle.properties
        id: extract_version
        run: |
          VERSION=$(grep '^version' gradle.properties | awk -F '=' '{print $2}' | tr -d ' ')
          if [ -z "$VERSION" ]; then
            echo "Error: Failed to extract version from gradle.properties"
            exit 1
          fi
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV


      # 上传构建产物为 Artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-build
          path: build/libs/*.jar
